### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by brurucy** [robclu/leapfrog#5]
Is there a specific reason as to why the single-threaded hash map does not implement `Clone` nor `Default`?

**Comment by robclu** [comment]
Hi,

No there isn't, other than that for `Clone` the use case has never came up, and there is  `new`, which should actually have been `Default` originally. I've added both implementations and tested clone works. If you run into any problems please create an issue.

**Comment by robclu** [comment]
I've updated the version on published crate to 0.2.2.

**Comment by brurucy** [comment]
I noticed that it cannot be used with stable, thanks anyways!
