### ISSUE TITLE
Available on the stable release channel?

### ISSUE THREAD

**Issue by spoorn** [robclu/leapfrog#7]
Does Leapfrog require nightly rust only?

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\Mikur\.cargo\registry\src\github.com-1ecc6299db9ec823\leapfrog-0.2.2\src\lib.rs:133:12
    |
133 | #![feature(allocator_api)]
    |            ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `leapfrog` due to previous error

```

**Comment by robclu** [comment]
Hi,

Yeah, currently it only works on nightly, but I am looking into allowing it to work on stable.

**Comment by mysteriouslyseeing** [comment]
Have you heard of the [allocator-api2](https://crates.io/crates/allocator-api2) crate?

**Comment by robclu** [comment]
Hi @Xuanwo, I have added support for stable (you'll beed to enable the `stable_alloc` feature). It's currently on the `allocator` branch, but I should be able to publish the updated version to crates.io later today.

**Comment by Xuanwo** [comment]
Great, thanks a lot!

**Comment by robclu** [comment]
Hi @Xuanwo, @mysteriouslyseeing, @spoorn,

Sorry this took so long. V0.3.0 has been published on crates.io with a feature flag for use one stable.

@mysteriouslyseeing, thank you for the suggestion for using the `allocator_api2` crate.
